### ISSUE TITLE
Telescope options

### ISSUE THREAD

**Issue by sho-87** [linux-cultist/venv-selector.nvim#104]
wondering if theres currently a way to pass opts to the telescope picker? the default paths to poetry venvs are really long on windows and makes it very hard to find the name of a venv, especially given poetry adds random numbers/letters to the end:

![image](https://github.com/linux-cultist/venv-selector.nvim/assets/5199715/a8e60436-5a66-47f8-8ada-b8a73626bce7)

telescope has a [path display option](https://github.com/nvim-telescope/telescope.nvim/blob/master/doc/telescope.txt#L268) to shorten paths however you want. in my case I'd probably just display the name of the venv only for easier reading

is there a way to do this?

I think I can set this option globally, but I dont want all of my pickers to be shortened in the same way

**Comment by linux-cultist** [comment]
In the new version I'm working on in the regexp branch, this is supported using a callback function. So for every venv that is listed in the telescope viewer, you can specify a function that gets called for each venv. And then in that function you can choose to return a shortened name or a changed name.

If you feel like checking it out, there is an example in the Readme for the regexp branch. But it's still under heavy development. :)

**Comment by linux-cultist** [comment]
Closing this since it should work fine in the regexp version of the plugin. Check the Readme for examples how to add your callback function to modify the filename how you want. You can do it either for all venvs found or for your own specific search only. It's described in the readme. Hope you get it to work, otherwise just ask and I can help.
