### ISSUE TITLE
All venv in one dir

### ISSUE THREAD

**Issue by steakhutzeee** [linux-cultist/venv-selector.nvim#108]
Hi, given the scenario where all venvs are in `$HOME/.venv` how should we configure the plugin?

I tried to set `path` as `$HOME/.venv`, `parents` to 0.But nothing is found.

I tried to set `path` to `$HOME`, `parents` to 0 and `name` to .venv but then the list will include every subdir of `$HOME/.venv`.

Is it possible to only list the "single" venvs and avoid "duplicates" ?

The structure is like:

`$HOME/.venv/`:
- venv1
- venv2
- venv3
- etc.

Thanks!

**Comment by mdic** [comment]
I have a similar situation, whereby all my venv folders begin with the following pattern:

`venv_`

as such I've tried using a regex pattern in the plugin config file, but to no avail - I'm not a Lua/nvim expert, and yet I have tried many different regex styles and none worked.
Any suggestion on how to make the plugin recognise each `venv_` folder as one venv, and listing only each main folder?
Thanks in advance

**Comment by linux-cultist** [comment]
Hey,

The plugin cant do this right now actually. It always wants to know the name of the venv to search for, and in this scenario you need it to be more dynamic (every folder under a certain path).

Since the plugin was created, it has changed so much to try and support more and more scenarios, and the code is getting a bit messy now and hard to understand. 

Im experimenting with a new version of the plugin where the entire search is much more configurable by the user. I will write more about it if Im happy with how its working out. :)

**Comment by linux-cultist** [comment]
I just tried and the regexp branch of the plugin can easily do this.

This `fd` command will list your venvs: `fd 'python$' ~/.venv`

```
/home/cado/.venv/venv1/bin/python
/home/cado/.venv/venv2/bin/python
/home/cado/.venv/venv3/bin/python
```

Add the fd command to your plugin configuration:
```

      require("venv-selector").setup {
        settings = {
          search = {
            my_venvs = {
              command = "fd 'python$' ~/.venv",
            },
          },
        },
      }
```

And they will show up in the telescope viewer.

![image](https://github.com/linux-cultist/venv-selector.nvim/assets/126409588/1ef95112-9339-43e9-98b0-09421a21d652)

Please note that in order to actually activate the venv, a python file must be opened so the LSP is running in neovim.

**Comment by linux-cultist** [comment]
Closing this since it should work fine in regexp version of the plugin. Reopen if it doesn't or if you have questions. :)
