### ISSUE TITLE
Unable to view/select python 3 versions 

### ISSUE THREAD

**Issue by ehxactly** [linux-cultist/venv-selector.nvim#112]
Hey all,

The plugin is installed and working, however, it is only listing Python 2* versions. 

Wondering how to resolve this as I have python 3.12.1 installed and 3.12.2 in the same /versions/ directory where the python 2* are.

Unsure why they aren't appearing in the UI?

```
return {
  'linux-cultist/venv-selector.nvim',
  dependencies = { 'neovim/nvim-lspconfig', 'nvim-telescope/telescope.nvim', 'mfussenegger/nvim-dap-python' },
  opts = {
    -- Your options go here
    name = "venv",
    auto_refresh = true
  },
  event = 'VeryLazy', -- Optional: needed only if you want to type `:VenvSelect` without a keymapping
  keys = {
    -- Keymap to open VenvSelector to pick a venv.
    { '<leader>vs', '<cmd>VenvSelect<cr>' },
    -- Keymap to retrieve the venv from a cache (the one previously used for the same project directory).
    { '<leader>vc', '<cmd>VenvSelectCached<cr>' },
  },
}
```
![image](https://github.com/linux-cultist/venv-selector.nvim/assets/110707311/db3fe88f-2b96-4b72-8eef-7c73e12409d8)

**Comment by ehxactly** [comment]
Now, I am seeing:

![image](https://github.com/linux-cultist/venv-selector.nvim/assets/110707311/8668bbe6-0e6e-4b4a-8f94-21e22f8aa76f)

**Comment by linux-cultist** [comment]
I'm working on a new version of the plugin where you can use regular expressions to filter out exactly the venvs you want to see yourself.

The current version is hard to maintain since supporting all the different venv managers was done by changing the code, and it has become a bit of a mess.

If you want to try the work-in-progress version, you can grab the branch called "regexp", and look in the Readme for that branch for a quick example how to configure. It all boils down to using fd with a regexp to filter out exactly what you want to see in the telescope viewer.

So if you know how to use fd, you know how to use the new version of the plugin, basically.

**Comment by linux-cultist** [comment]
I think you should try the `regexp` branch now, since im pretty sure it will pick up all your .pyenv pythons without any configuration even. It looks in `~/.pyenv/versions` by default and will list all pythons there.


Configuration for lazy.nvim:

```
return {
  "linux-cultist/venv-selector.nvim",
    dependencies = {
      "neovim/nvim-lspconfig", 
      "mfussenegger/nvim-dap", "mfussenegger/nvim-dap-python", --optional
      { "nvim-telescope/telescope.nvim", branch = "0.1.x", dependencies = { "nvim-lua/plenary.nvim" } },
    },
  lazy = false,
  branch = "regexp", -- This is the regexp branch, use this until its merged with the main branch later
  config = function()
      require("venv-selector").setup()
    end,
    keys = {
      { ",v", "<cmd>VenvSelect<cr>" },
    },
},
```

**Comment by linux-cultist** [comment]
Closing this since it should work in the regexp branch, and if it doesn't, reopen the issue. Thank you!
