### ISSUE TITLE
Make `python_parent_dir` Not Work Globally

### ISSUE THREAD

**Issue by atomsi7** [linux-cultist/venv-selector.nvim#128]
As shown in the code snippet below, `python_parent_dir` is set by the conda `parent_dir`:
https://github.com/linux-cultist/venv-selector.nvim/blob/6a1b15eb35bbb827b6db428055087e2dbf32838f/lua/venv-selector/system.lua#L62-L71
In a situation I encountered, the `python_parent_dir` for conda is `''` (which is just in the path), but I would like the `python_parent_dir` for pyenv, venv, etc. to still be `Scripts`.

**Comment by linux-cultist** [comment]
Hi!

There is a rewritten version of the plugin that handles this much better I believe. Check the Readme and try the `regexp` version. :)

The reason I rewrote it is exactly because of issues such as this one. Let me know what you think!

Closing this issue but comment on it when you have tried it please. All feedback is very welcome.
