### ISSUE TITLE
[Bug] Notification shows up twice on cached venv with copilot alongside lsp

### ISSUE THREAD

**Issue by TroySigX** [linux-cultist/venv-selector.nvim#135]
Steps to reproduce:
1. Set option `notify_user_on_venv_activation = true` and `enable_cached_venvs = true`
2. Open a file which has a venv activated before
3. A notification should show up now
4. Press some random command (e.g `:VenvSelect`), an identical notification shows up again.

**Comment by TroySigX** [comment]
I notice that the second noti only shows up when I use [copilot.lua](https://github.com/zbirenbaum/copilot.lua) alongside lsp. So I guess that the number of times notification shows up is the number of lsps configured for the buffer?

**Comment by linux-cultist** [comment]
Your second comment was very helpful in understanding this, so thank you for that. 

Yes, its notifying for each LSP configured for the buffer. 

It would be better if it just notified once and listed the LSP's used for the buffer in the message.

How do the messages look for you now when its showing a second notification? I cant test since I dont have a subscription. I used to have it though but felt Chat Gpt was better. :)

**Comment by TroySigX** [comment]
Like this:
![image](https://github.com/linux-cultist/venv-selector.nvim/assets/88051085/2753e124-342b-4189-b453-d0589a173205)

**Comment by linux-cultist** [comment]
Update now and see if the problem is fixed. The same notification about lsp activation is not allowed now if it occurs within 1 second of the previous one.

**Comment by TroySigX** [comment]
Fixed, thanks!

**Comment by TroySigX** [comment]
Fixed, thanks!
