### ISSUE TITLE
 can you please add supports virtual environments created in uv as well?

### ISSUE THREAD

**Issue by lazyzyf** [linux-cultist/venv-selector.nvim#154]
https://github.com/astral-sh/uv

**Comment by linux-cultist** [comment]
The `regexp` version of the plugin will find these automatically since they don't have special location. They are just named `.venv` in your working directory and the plugin will find those by default.

So switch to the regexp version. There is info in the Readme at the top. :)

**Comment by lazyzyf** [comment]
Hi. the .venv folder is in my home directory in windows OS, so the regexp can find it by default as well?

**Comment by linux-cultist** [comment]
By default, the regexp version will look in your current working directory (the path where you opened neovim) and all folders below it. Bur the home directory usually contain so many files that it may be slow to search all of them.

You can define your own search though and disable the cwd search, to make the plugin look exactly in your home folder and no folders below it (as an example).

There is some info in the readme how to do this but you may have to experiment a bit with `fd` syntax to get it how you want.:)

**Comment by smabbasht** [comment]
I use `uv` and I have a specific location where I keep all my venvs i-e `~/uv-envs/`
Can you please direct me to the part through which I could include this in the search, 
Also, since I don't use other venv managers, Can I simply change one of them's path as defined in `system.lua` to `~/uv-envs`, would that work, if so. how?
TIA
