### ISSUE TITLE
Issue when trying to search venv in windows powershell

### ISSUE THREAD

**Issue by DaveanandMannie** [linux-cultist/venv-selector.nvim#170]
I'm not sure what broke as it will still select cached venvs but not new venvs. Over the weekend I switched from Powershell 5 to 7. I tried it in both and the same error. It seems like its not properly handling `\` in Windows but I don't see why it stopped when I haven't really changed the settings much since last week, and it was working a few days ago. 
This could very well be a config issue on my part  
I'm on `Wezterm`, `Powershell  7.4.5`, using `lazyvim` 
my lockfile : `"venv-selector.nvim": { "branch": "regexp", "commit": "4cf9fdebe3daca2b4459a275a123b2536fa60388" },`, 
plugin settings
```
  {
    "linux-cultist/venv-selector.nvim",
    branch = "regexp",
    cmd = "VenvSelect",
    enabled = function()
      return LazyVim.has("telescope.nvim")
    end,
    opts = {
      settings = {
        options = {
          notify_user_on_venv_activation = true,
        },
      },
    },
    ft = "python",
    keys = { { "<leader>cv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv", ft = "python" } },
  },
```
```
   Error  9:11:50 PM msg_show.lua_error   VenvSelect Error executing Lua callback: ...l/nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Vim:Error executing Lua callback: Vim:E903: Process failed to start: no such file or directory: "C:/Program"
stack traceback:
	[C]: in function 'jobstart'
	...ata/lazy/venv-selector.nvim/lua/venv-selector/search.lua:122: in function 'start_search_job'
	...ata/lazy/venv-selector.nvim/lua/venv-selector/search.lua:194: in function 'run_search'
	...ata/lazy/venv-selector.nvim/lua/venv-selector/search.lua:212: in function 'New'
	...y/venv-selector.nvim/lua/venv-selector/user_commands.lua:11: in function <...y/venv-selector.nvim/lua/venv-selector/user_commands.lua:9>
	[C]: in function 'cmd'
	...l/nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <...l/nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>
stack traceback:
	[C]: in function 'cmd'
	...l/nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: in function <...l/nvim-data/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:16>
9:11:41 PM msg_showcmd A
```

If you could point me to the log files ill gladly share them but I cant seem to find them 
```
 ./
├──  CONTRIBUTING.md
├──  LICENCE.md
├──  lua/
│   └──  venv-selector/
│       ├──  cached_venv.lua
│       ├──  config.lua
│       ├──  gui.lua
│       ├──  hooks.lua
│       ├──  init.lua
│       ├──  logger.lua
│       ├──  path.lua
│       ├──  search.lua
│       ├──  user_commands.lua
│       ├──  utils.lua
│       ├──  venv.lua
│       └──  workspace.lua
├──  README.md
├──  stylua.toml
└──  venvselect-2024.png
PS C:\Users\support\AppData\Local\nvim-data\lazy\venv-selector.nvim>
```
edit:
I also checked in the default windows cmd and I still get the same error.
edit 2:
I swapped to commit `c43dc6bf8c7e7cf124a991775ed3defe87112d3a` and I still get the error which leads me to believe there is something wrong somewhere with my setup....  I don't know where the `C:/Program` is being evaluated

**Comment by linux-cultist** [comment]
You can try setting the option `debug = true`. It will give you a new command called `:VenvSelectLog` that you can run and see the log. Maybe it gives some more useful information. Its quite tricky with paths on windows since they are handled differently by different shells it seems.

You can also try the branch called `windows_lua_table` instead of `regexp` - it attempts to run windows searches without using any shell and may therefore avoid problems like the one you are getting. Ive only tested it on Powershell and CMD myself so far but it seems to work there.

**Comment by DaveanandMannie** [comment]
Sure if I get time at work I'll give it a shot. Latest will be today 9pm EDT

**Comment by DaveanandMannie** [comment]
> The `windows_lua_table` branch is very temporary and wont exist for long - it will be merged into regexp when its ready. But you can try it and see if it works. It would be nice to hear if it makes a difference for you or not.

`Debug` didn't give me any more info than than noice did. However switching over to the  `windows_lua_table` did seem to fix the issues for venv-selector. Although I do think something changed either on windows or lazy because my BasedPyright is  in single file mode rather than having a workspace dir. Regardless this  specific issue resolved, Thanks for the help!! I'm not sure if I should close this issue; raising issues on here is a bit new to me.

**Comment by linux-cultist** [comment]
You can enable debug, and then bring up venvselect, and then run `:VenvSelectLog` afterwards and you should see a full window with logs. :) The plugin logs hundreds of lines of info usually.

The single file mode is usually caused by your lsp (basedpyright) not finding a workspace folder. You may have opened neovim in a folder that doesnt have a git repository or some other way for basedpyright to know its a project folder for python? Then it will just run in single file mode, since its not aware of any other files. The `windows_lua_table` shouldnt change anything about that so I think maybe you just opened neovim in a different folder this time? 

I will merge in the `windows_lua_table` branch now since I think it should improve things in general for windows users. But we can keep this issue open until you feel comfortable that the plugin is working correctly for you.

**Comment by DaveanandMannie** [comment]
The plugin works; It was an issue with my lazy config `vim.o.shell = "C:/Program Files/PowerShell/7/pwsh.exe"` even running commands directly with `:!` didn't work. 

The `:VenvSelectLog`  didn't  work as I placed it in the wrong place in the plugin... Sorry about that

As for the LSP issue, your right this plugin had nothing to do with it, I was more leaning towards it being a symptom of the same issue that was causing this plugin to not work as expected.  I hadn't init a repo for this specific  project. Again sorry about that, I didn't know that's how it was searching for the workspace, I assumed it was doing something similar with `fd` 

I think  prior to your merge would be properly handling the `vim.o.shell`  value. For now I will symlink the folder and see if that works in my setup.

Regardless your merge definitely works for me 

Thanks for your patience

**Comment by linux-cultist** [comment]
Excellent. It's not so easy to know all this stuff about lsp and how it works. Took me a long time to even know what it does.

I'm happy the plugin works for you now. See you around. :)
