### ISSUE TITLE
Venv path not loaded nor shown in options

### ISSUE THREAD

**Issue by pinkfloydsito** [linux-cultist/venv-selector.nvim#172]
Hi, I was trying to do the default configuration in LazyVim, however I am not sure why the venv I am creating in my directory using pyenv is not being found.

```lua
  {
    "linux-cultist/venv-selector.nvim",
    branch = "regexp", -- Use this branch for the new version
    cmd = "VenvSelect",
    enabled = function()
      return LazyVim.has("telescope.nvim")
    end,
    opts = {
      settings = {
        options = {
          search = true,
          parents = 0,
          auto_refresh = true,
          notify_user_on_venv_activation = true,
          search_workspace = true, -- If you want to search in the workspace/project root
          search_dirs = { ".venv", "venv", "env"}, -- Add custom venv folder names here
        },
      },
    },
    --  Call config for python files and load the cached venv automatically ft = "python",
    keys = { { "<leader>cv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv", ft = "python" } },
  },

```

This is the files in my directory:
<img width="386" alt="Screenshot 2024-09-12 at 6 25 40 PM" src="https://github.com/user-attachments/assets/aad42e69-88a2-4953-9962-4c19a21fef46">

somehow i refresh and I can't see the nearest venv folder that I have, the same result I got when moving it to the previous directory.

<img width="1123" alt="Screenshot 2024-09-12 at 6 25 06 PM" src="https://github.com/user-attachments/assets/083cc270-3906-42c5-acb9-64a325207da2">

What is wrong? Is there a setting missing?

**Comment by linux-cultist** [comment]
It looks like you are using the settings from the old `main` branch with the `regexp` branch and that will not work - the new branch is completely rewritten from scratch with new settings and options.

There is a new readme in the `regexp` branch you can look through: https://github.com/linux-cultist/venv-selector.nvim/tree/regexp

The plugin should find the `venv` folder in your project directory though since there is a default search for that called `cwd`:

```
                cwd = {
                    command = "$FD '/bin/python$' $CWD --full-path --color never -HI -a -L -E /proc -E .git/ -E .wine/ -E .steam/ -E Steam/ -E site-packages/",
                },

```

But that one only looks in your current directory. So if you change neovim working directory to something else (like going into a subfolder with `cd`), then the CWD search will not find things in your parent folder anymore.

You can define your own searches though that always look in a specific folder, no matter what directory you are in.

So for example:

```
      require("venv-selector").setup {
        settings = {
          search = {
            home_dir_venvs = {             -- name of the search becomes "home_dir_venvs"
              command = "fd /bin/python$ ~ --full-path",  -- the fd command to execute to find your venvs
            },
          },
        },
      }
```

On my computer the above fd command gives:
```

 π ~ ❯ fd /bin/python$ ~ --full-path
/home/cado/venvs/venv/bin/python
```

So you can experiment and see what works for you, and add it to VenvSelect.

**Comment by linux-cultist** [comment]
Im closing this issue but reopen if you still have problems. Thank you!
