### ISSUE TITLE
config options in the readme.md needs to be improved

### ISSUE THREAD

**Issue by qizidog** [linux-cultist/venv-selector.nvim#42]
Some discription of options is not complete, just search in `README.md`

> -- search_venv_managers (default: true). Will search for Poetry and Pipenv virtual environments in their
> -- default location. If you dont use the default location, you can
> search_venv_managers = true,

Additionally, there are some options that are not mentioned in readme, such as

```lua
{
  poetry_path = system.get_venv_manager_default_path("Poetry"),
  pipenv_path = system.get_venv_manager_default_path("Pipenv"),
  pyenv_path = system.get_venv_manager_default_path("Pyenv"),
  anaconda_path = system.get_venv_manager_default_path("Anaconda"),
  venvwrapper_path = system.get_venv_manager_default_path("VenvWrapper"),
}
```

Suggest writing the function of the parameter into `config.lua`.

**Comment by qizidog** [comment]
Based on my observation, configuring the several `path` variables mentioned above seems to have no practical effect. Perhaps users should be allowed to prohibit unnecessary search paths to avoid excessive search time consumption

**Comment by linux-cultist** [comment]
Venvwrapper and Anaconda support was recently added and I havent updated the README (thanks for the reminder!).

Changing them to something else should have an effect and the plugin should look in those paths instead of the default paths. Can you share an example that doesn't work?

**Comment by qizidog** [comment]
Perhaps I didn't express myself clearly enough, I mean that the `search_venv_managers` option seems unclear, the content after **"you can"** is missing.

> -- search_venv_managers (default: true). Will search for Poetry and Pipenv virtual environments in their
> -- default location. If you dont use the default location, you can
> search_venv_managers = true,

Since I only use conda, my original idea was to avoid searching other directories outside of the conda environment (I can always search for twenty to thirty venvs).

I **partly** achieved my goal by setting `search=false` (actually by `search_venv_managers`), but I still believe that the `search` option is somewhat confusing and the `path` option takes no effect.

All my config is as followed:

```lua
{
    "linux-cultist/venv-selector.nvim",
    opts = {
        dap_enabled = true,
        search = false,
        -- parents = 0,
        search_venv_managers = true,
        -- path = os.getenv("CONDA_PREFIX") .. "/envs",
    },
    keys = { { "<leader>cv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv" } },
},
```



In my opinion, the relationship between the three options `path`, `search_venv_managers`, and `search` needs to be reconsidered. For example, when `path` is set, all other paths should not be searched.

**Comment by qizidog** [comment]
If I set `search = false`, `path = os.getenv("CONDA_PREFIX") .. "/envs"` and `search_venv_managers = false`, no venv would be found.

**Comment by linux-cultist** [comment]
> If I set `search = false`, `path = os.getenv("CONDA_PREFIX") .. "/envs"` and `search_venv_managers = false`, no venv would be found.

This is correct behavior since Conda is seen as a venv manager by the plugin.

But yes, I agree with what you are saying in this thread. The plugin originally started out as just supporting venv folders and with time, I added support for more things. So now the options are somewhat confusing because I didnt want to break backwards compatibility.

> In my opinion, the relationship between the three options path, search_venv_managers, and search needs to be reconsidered. For example, when path is set, all other paths should not be searched.

The `path` option is only supposed to be used when searching for manually created venvs (not conda, pipenv, poetry etc). Its basically how you tell VenvSelect to not go looking in `project_folder`'s parent directories for *manually created venvs*, and instead just use the `path` you set for the projects. 

For conda, you should set `anaconda_path` to where your conda managed venvs can be found. `search_venv_managers` need to be true, but `search` can be false if you dont want to look for manually created venvs.

With all these options, its even more important that the README is clear and easier to understand. I will take a look at it and add examples to hopefully make it more clear. I can completely understand the frustration of not getting a plugin to work because its complicated to understand. I have been there myself many times. :)

**Comment by qizidog** [comment]
That's brilliant! This project has already provided me with a lot of convenience 😄
