### ISSUE TITLE
how to change python interpreter in neotest-python

### ISSUE THREAD

**Issue by YAOYouYou** [linux-cultist/venv-selector.nvim#45]

**Comment by linux-cultist** [comment]
Hi,

I havent used neotest-python but i read the config example, and it has a setting called `python` to set the python interpreter. 

VenvSelect gives you the selected python interpreter if you call `require("venv-selector").get_active_path()`.

So what is needed is some way to update neotest-python when you select a new venv. You probably cant call its setup() function more than once, so check with the author if there is a way to update which python interpreter it should use.

Hope you understand what i mean, otherwise ask. :)

**Comment by YAOYouYou** [comment]
thank you very much
