### ISSUE TITLE
The directory where pyenv installs python is the same as the directory where pyenv-virtualenv puts venv.

### ISSUE THREAD

**Issue by yolong-lin** [linux-cultist/venv-selector.nvim#52]
I think the plugin should only show venv directory.

**Comment by linux-cultist** [comment]
Hi,

Im not sure what this means. You mean removing the last `/venv` part from the listed venvs?

**Comment by yolong-lin** [comment]
`pyenv install 3.10.12` install python 3.10.12 in `~/.pyenv/versions`. 
`pyenv virtualenv 3.10.12 venv-31012` create a virtual environment in `~/.pyenv/versions`.

<img width="1159" alt="截圖 2023-08-20 下午10 30 52" src="https://github.com/linux-cultist/venv-selector.nvim/assets/32055974/338dc2f3-bf48-4b93-90ea-2ff6efa4a005">

I mean, only `venv-31012` is virtual environment. VenvSelector should not display `3.10.12`

**Comment by linux-cultist** [comment]
Oh ok, I see what you mean now. Thank you. Im not too familiar with pyenv, and I didnt know it would install python itself inside the same path. I will see what i can do. :)

**Comment by linux-cultist** [comment]
This is fixed now in the latest commit. The plugin excludes any  '3.*.*' paths when searching for venv managers. Its not a perfect solution but `fd` doesnt understand regexp in excluding paths, so this was the best I could do without having my own filter function and do a secondary filter inside lua.

Hopefully people dont name their managed venvs in the same way as python versions, because then they wont show up.

**Comment by yolong-lin** [comment]
Maybe we can check `pyvenv.cfg` if exists in the venv folder.

**Comment by linux-cultist** [comment]
You mean to only exclude the path if there is a pyvenv.cfg in the venv folder?
