### ISSUE TITLE
[Feature request]: Multiple backends for visual picker

### ISSUE THREAD

**Issue by TroySigX** [linux-cultist/venv-selector.nvim#55]
I notice that `venv-selector` only uses `Telescope` as its visual picker. It would be great if it migrate to something more general, like `vim.ui.select`, that way, users can choose between different pickers like `nui.nvim` or `fzf-lua`.

**Comment by linux-cultist** [comment]
I agree and I'm actually using fzf-lua myself for most pickers, but couldn't find a good example how to populate a picker.

But I would welcome PR's or even links to good docs. Telescope was just the easiest to get started with.

**Comment by TroySigX** [comment]
Would using [dressing.nvim](https://github.com/stevearc/dressing.nvim) solve your problem?

**Comment by linux-cultist** [comment]
I dont think I will add support for a different viewer. It would not be so hard to do since in the new regexp version, the GUI code is very small and self-contained. But I dont know this area very well and I rather focus on the core plugin.

But if anyone wants to contribute a PR, feel free to do so!
