### ISSUE TITLE
VenvSelectCached Command is not working

### ISSUE THREAD

**Issue by mohit2152sharma** [linux-cultist/venv-selector.nvim#75]
So I am using miniconda for my virtual environments and I have the plugin set up as follows:

```lua
{
    "linux-cultist/venv-selector.nvim",
    opts = {
      search = false,
      anaconda_envs_path = os.getenv "HOME" .. "/miniconda3/envs",
      auto_refresh = true,
      -- search_venv_managers = false,
      search_workspace = false,
    },
    keys = { { "<leader>lv", "<cmd>:VenvSelect<cr>", desc = "Select VirtualEnv" } },
  },
```
I cd into my python project and select a virtual environment. But when I come back again to that directory, and run the command `VenvSelectCached` it throws the error, `Not an editor command`. However, if I select the virtual environment and then run `VenvSelectCached` it works fine. 

Not sure if I am doing everything correct. I don't know know much lua, but when I was browsing through the functions, ([this one](https://github.com/linux-cultist/venv-selector.nvim/blob/48c9cd0dbc0ce3cc02fd6164e4f665dba338a3ec/lua/venv-selector/venv.lua#L305)), it seems to like, we need to pass `cache_file` in the `opts`?

**Comment by linux-cultist** [comment]
Sorry for the delays on this one. I managed to catch a very bad cold for the last week here, so haven't been at my computer for almost a week now. Hopefully soon I can have a look at this and figure out what's going on. I didn't write the code for VenvselectCached myself, it was a PR by another user a long time ago, so I have to look into it a bit and see what could be the issue. :)

**Comment by mohit2152sharma** [comment]
Hey, no issues, please take care of your health. It's not blocking anything for me, so it's okay if takes time. No need to rush, at the cost of your health.

**Comment by mennohofste** [comment]
Are you running the `VenvSelectCached` command directly? 

If so, this happens because `lazy.nvim` loads the plugin lazily, so the commands are not loaded on startup. You can only run the `VenvSelectCached` command only after the plugin is loaded.

I can come up with 3 solutions:
1. bind the command to a key similar to your `VenvSelect`. Lazy loads the plugin when you press the key
2. run the lua command `lua require("venv-selector").retrieve_from_cache()`, the require essential loads the plugin
3. add `lazy = false` to your config to avoid lazy loading the pluging (https://github.com/folke/lazy.nvim#-plugin-spec)

There is probably more solutions. I imagine adding an event trigger to your config could also work, though I could not get it to work for me immediately.

Hope this helps!

**Comment by voider1** [comment]
@mennohofste For me both of the commands are not working, I tried all your suggestions, but to no avail. Any other suggestions?

**Comment by mohit2152sharma** [comment]
@mennohofste , thanks a lot. The issue was exactly, what you explained. I went ahead with option 3 for the time being, but as I am reading more about `lua`, I feel like there should be a way to automatically load the virtual environment, when you cd into a project directory (if it's available in cache). 

@voider1 , it may be because of how you are setting up the plugin (as it was for me), could you share, more details about how you are setting it up?

**Comment by linux-cultist** [comment]
Amazing to see this closed, thanks a lot @mennohofste and @mohit2152sharma for figuring out what the issue was. :)
